export const MAIN_ROUTE = '/' 
export const ANIMALS_AND_PASTURES_ROUTE = '/animalsandpastures'
export const CROPS_AND_FIELDS_ROUTE = '/cropsandfields'
export const FIELDJOBS_ROUTE = '/fieldjobs'
export const EQUIPMENT_AND_REPAIRS_ROUTE = '/equipmentandrepairs'